# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml
# https://www.ianlewis.org/en/building-go-applications-google-container-builder

steps:
  - id: "Executando teste"
    name: "golang"
    args:["go", "test"]
    env:
      - "GOPATH=${_GOPATH}"

  - id: "Executando App"
    name: "golang"
    args: ["go", "run", "soma.go"]
    env:
      - "GOPATH=${_GOPATH}"
  
  - id: "Compilando app"    
    name: "golang"
    args: ["go", "build", "-ldflags", "'-w -s -extldflags \"-static\"'", "-a", "-o", "soma" ]
    env:
      - "GOPATH=${_GOPATH}"      
      - "CGO_ENABLED=0"
      - "GOOS=linux"
      - "GOARCH=amd64"

  - id: "Gerando imagem"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/goapp-soma:latest"
      - "."
images:
  - "gcr.io/$PROJECT_ID/goapp-soma:latest"
substitutions:
  _GOPATH: github.com/jean-andrade/fullcycle-desafio-ci-golang